//
// Created by Oz on 5/14/2020.
//

#ifndef COMP5421_ADVANCED_PROGRAMMING_ASSIGNMENT_1_TEXT_H
#define COMP5421_ADVANCED_PROGRAMMING_ASSIGNMENT_1_TEXT_H


class Text {

};


#endif //COMP5421_ADVANCED_PROGRAMMING_ASSIGNMENT_1_TEXT_H
